language: node_js
node_js:
  - "10"
services:
  - docker
branches:
  only:
    - master
    - dev

script:
  - npm test
  - tsc
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t "pea3nut/point-hub:${TRAVIS_BRANCH}" .
  - docker push "pea3nut/point-hub:${TRAVIS_BRANCH}"
